# Top-level Ruff configuration, can be extended per directory as the
# configuration is hierarchical.

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

line-length = 120
indent-width = 4

# Python 3.11.x
target-version = "py311"

# Use short output
output-format = "concise"

[lint]
# Rules https://beta.ruff.rs/docs/rules/
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
]

# Linting error codes to ignore
ignore = []

# Linting error codes to ignore on a per-file basis
[lint.per-file-ignores]
"__init__.py" = ["F401", "E501"]
